/*
 * DO NOT EDIT THIS FILE
 */
module.exports = {

    SUCCESS_0       : '0',            /* no success status code */
    SUCCESS_200	    : '200',          /* success status code */
    ERROR_0         :  '0',           /* no error status code */
    ERROR_400    	: '400',          /* bad request error status code */
    ERROR_401       : '401',          /* parameter missing error status code */
    ERROR_402       : '402',          /* configration error status code */
    ONETIME 		: 'onetime',
    SCHEDULE 		: 'schedule',
    EMAIL			: 'email',
    SMS 			: 'sms',
    WEBPUSH 		: 'webpush',
    MANDRILL		: 'mandrill',
    TWILIO			: 'twilio',
    BASIC			: 'basic',
    ADVANCE         : 'advance',
    TEMPLATE 		: 'template',
    SENDGRID        : 'sendgrid'
}